### ISSUE TITLE
SurrealRecordAlreadyExitsException not thrown when using unique index

### ISSUE THREAD

**Issue by sillen102** [surrealdb/surrealdb.java#10]
SurrealRecordAlreadyExitsException is not being thrown when attempting to add an entity with a value that would violate the unique constraint when a unique constraint index is applied.

Instead the super SurrealException is thrown.

It might not be intended but I would have expected the more specific SurrealRecordAlreadyExitsException to be thrown when violating the unique constraint. At least it would have been better to have some kind of specific exception for that case to be able to properly implement error handling and responses in ones application. Especially since the generic SurrealException does not have an error message that could be used.

**Comment by phughk** [comment]
Solved by @coder966
