### ISSUE TITLE
No releases yet

### ISSUE THREAD

**Issue by NapoleonBorn2Party** [surrealdb/surrealdb.java#2]
There is no jar available in https://github.com/surrealdb/surrealdb.java/releases

**Comment by coder966** [comment]
Hi NapoleonBorn2Party.

For the time being, you can either:

Option 1: Build the jar yourself by:
- download the code
- run `./gradlew fatJar`
- the jar will be at `build/libs/surrealdb-0.1.0.jar`

Option 2: download it from my fork repo at: https://github.com/coder966/surrealdb.java-wip/releases/tag/v0.1.0

Will try to submit a PR to automate the release creation.

**Comment by hugo4715** [comment]
If you are using maven you can use Jitpack:
```
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>

```

Specify a commit hash to use in the version:
```
<dependency>
    <groupId>com.github.surrealdb</groupId>
    <artifactId>surrealdb.java</artifactId>
    <version>aad7811f9f</version>
</dependency>
```

More info on https://jitpack.io/

**Comment by phughk** [comment]
We now release to maven central. To anyone reading, please have a look at the updated documentation https://surrealdb.com/docs/integration/libraries/java
Thanks for handling the initial builds and releases @coder966 ! :) That was awesome of you
