### ISSUE TITLE
Align API with Rust API

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#37]
Align the API to follow the available Rust functionality. Currently, we have a few functions, and they don't necessarily fit the Rust API. This should be fixed for a more predictable experience.

Note for contributors: this does not need to be done in one PR. If you would like to pick a single function to align, feel free to do so! For examples on how they differ please refer to the [Rust API documentation](https://surrealdb.com/docs/integration/libraries/rust) and the [Java API documentation](https://surrealdb.com/docs/integration/libraries/java)

**Comment by emmanuel-keller** [comment]
SurrealDB driver v0.2.0 has been released. The new API  is now aligned with the other clients.
