### ISSUE TITLE
Remove SurrealWebSocketConnection

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#39]
The class `SurrealWebSocketConnection` is unnecessary. We should instead use URI's which also support custom protocols for `tikv://` and `memory`. Probably can just use `URI` instead.
On top of that, the connection should not "connect". The driver connects using the address. The OOP model is unusual.

**Comment by emmanuel-keller** [comment]
Superseded by SurrealDB driver v0.2.0
