### ISSUE TITLE
Questions regarding some details

### ISSUE THREAD

**Issue by dodalovicgran** [surrealdb/surrealdb.java#48]
Based on the docs:

```java
import com.surrealdb.connection.SurrealWebSocketConnection;
import com.surrealdb.driver.SyncSurrealDriver;

import java.util.List;
import java.util.Map;

public class App
{
    public static void main( String[] args )
    {
        SurrealWebSocketConnection conn = new SurrealWebSocketConnection("localhost", 8000, false);
        conn.connect(5);
        SyncSurrealDriver driver = new SyncSurrealDriver(conn);
        driver.signIn("root", "root");
        driver.use("namespace-name", "database-name");
        String tableName = "user";
        driver.delete(tableName);
        User tobie = driver.create(tableName, User.builder().name("Tobie").build());
        User jaime = driver.create(tableName, User.builder().name("Tobie").build());
        List<Map<String, String>> updates = driver.update(jaime.id, Map.of(
                "name", "Jaime"));
        List<User> allUsers = driver.select(tableName, User.class);
        System.out.printf("All users = %s", allUsers);
        conn.disconnect();
    }
}
```

* What's the lifetime of the `conn`?
* What's the lifetime of the `driver`?
* What about thread safety?

Thank you!

**Comment by phughk** [comment]
Heya!

Java doesn't have a concept of lifetimes (when memory gets destroyed/deallocated once it is no longer accessible). Instead, memory can be accessed from anywhere, but once it is detected during runtime that it cannot be accessed, it will be garbage collected (deallocated).

Conn and driver are both candidates for deallocation once they leave scope at the end of the main method. At the end of the main method, the program terminates anyway, which will probably trigger deallocation.

Regarding thread safety - all of this runs with memory assigned per invocation so there are no issues. The contention on the websocket is handled by the client libraries which are safe.

Closing as this isn't an issue and the questions have been addressed.

**Comment by dodalovic** [comment]
Actually my question was more if the conn and driver can be reused during the lifetime of an app? Are they expensive to create?

**Comment by dodalovic** [comment]
Actually my question was more if the conn and driver can be reused during the lifetime of an app? Are they expensive to create?

**Comment by dodalovicgran** [comment]
Actually, my question was more if the conn and driver can be reused during the lifetime of an app? Are they expensive to create?

**Comment by phughk** [comment]
They can absolutely be reused throughout the lifetime of the app and that is recommended. They are not particularly expensive to create, though they do initialise a TCP connection (websocket) or several (HTTP) which you will want to reduce.

**Comment by phughk** [comment]
Then the driver needs to be reinitialised or reconnected. I don't think we have reconnection logic, but adding it might be possible.
