### ISSUE TITLE
REQ: Update GitHub workflow to test using integrationTest in addition to unit test

### ISSUE THREAD

**Issue by eharrow** [surrealdb/surrealdb.java#50]
Merged code from a PR should pass quality checks before merging.  At present the level of testing we have is integration and not unit (we need both) however the build does not run the integration tests but merely the unit tests which are lacking and coverage.

Update test target to `gradle integrationTest` which will run the unit `test` target  before the integration tests.

**Comment by eharrow** [comment]
See https://github.com/surrealdb/surrealdb.java/pull/51

**Comment by phughk** [comment]
Thanks for resolving @eharrow ! 🎉
