### ISSUE TITLE
Could not resolve com.surrealdb:surrealdb-driver:0.1.0.

### ISSUE THREAD

**Issue by munishchouhan** [surrealdb/surrealdb.java#57]
I am adding java driver as a dependency in my project
But getting error: Could not resolve com.surrealdb:surrealdb-driver:0.1.0.

**Comment by phughk** [comment]
Hey. The driver is definitely published, so you either have networking issues or config issues.

https://central.sonatype.com/artifact/com.surrealdb/surrealdb-driver/0.1.0

I will close this ticket as based on the above information, it looks like something you may have set up incorrectly. But please comment about more details - perhaps this is some issue we are not aware of.

**Comment by munishchouhan** [comment]
Yes, the issue was because of the Java version of binary needs to be 17 or later

**Comment by phughk** [comment]
Good point, thanks for feeding that back! We may reduce the java version requirement in that case. I don't think we are using any functionality beyond 8 anyway. Will create a ticket for this, thanks!

Which version java are you using @munishchouhan ?

**Comment by phughk** [comment]
Created https://github.com/surrealdb/surrealdb.java/issues/58 from this

**Comment by munishchouhan** [comment]
Java 11
