### ISSUE TITLE
Feature: Implement HTTP protocol for refactor API

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#61]
### Is your feature request related to a problem?

We would like a synchronous HTTP(S) protocol implemented for the refactor of the API. 

The main ways that this would differ from the current implementation are
- shared processing of messages between plaintext websockets and stateless HTTP
- correct type casting to the appropriate rust-like type
- correct parameter handling

This is a big ticket, so do as much as you can and then create more Unimplemented tickets for the missing functionality.

### Describe the solution

The HTTP api should at minimum
- connect
- authenticate (via the Unauthenticated interface)
- execute queries (for example, `INFO FOR KV` only at the moment). This can be a stretch goal.

### Alternative methods

I would rather not lift code from the existing implementation.

If possible, we should also use netty for perf gains.

### SurrealDB version

SurrealDB beta-9; java driver commit 50aa1d61c4879ed52cda099e3be4324bd97d3bd6

### Contact Details

hugh@surrealdb.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emmanuel-keller** [comment]
SurrealDB driver v0.2.0 is now delegating the transport to the embedded Rust SDK.
