### ISSUE TITLE
Feature: Handle parsing of JSON into Value type

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#63]
### Is your feature request related to a problem?

The SurrealDB server sends JSON responses that match [Value](https://github.com/surrealdb/surrealdb/blob/main/lib/src/sql/value/value.rs#L108-L152) (enum) types.

Obviously, JSON is lossy. But it would be really cool if we could convert it to the java Value type declared in the refactor package.

### Describe the solution

Handle strings, numbers, objects, and arrays for JSON into the Value type.

### Alternative methods

This is open to interpretation. Feedback on the request. Best advice is to keep it simple so we can change it when we need to.

### SurrealDB version

SurrealDB beta-9; java driver commit 50aa1d6

### Contact Details

hugh@surrealdb.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emmanuel-keller** [comment]
SurrealDB driver v0.2.0 delegates the transport layer to the embedded Rust SDK
