### ISSUE TITLE
Feature: Select Model without using Record-IDs

### ISSUE THREAD

**Issue by 047massi** [surrealdb/surrealdb.java#64]
### Is your feature request related to a problem?

Select a Model by using e.g. a Username instead of a Record ID

### Describe the solution

i think it would be better to select a model by like using a username from a column instead to use a record id.

### Alternative methods

I came to an idea to add something like a `.where("key", "value")` method to the end of driver.select(...) Example: `User user = driver.select("table", User.class).where("key", "value")`)

### SurrealDB version

1.0.0-beta.9+20230402.5eafebd for windows on x86_64

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by emmanuel-keller** [comment]
With version 0.2.0, the select method is now declined with several variants, allowing to `select` a table.

https://surrealdb.github.io/surrealdb.java/javadoc/com/surrealdb/Surreal.html#select(java.lang.Class,java.lang.String)
