### ISSUE TITLE
Feature: Implement use for stateless (http) client implementation

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#67]
### Is your feature request related to a problem?

We would like to have functionality similar to #66 but for the stateless HTTP implementation.

This would also use netty, which, as of writing, is currently missing.

### Describe the solution

Add netty handlers for use endpoints and functionality. Use the JS implementation as a reference.

### Alternative methods

Please discuss in the discord java channel if you would like a different method. We would like to use netty for this though.

### SurrealDB version

1.0.0-beta.9+20230821.0665e1b7

### Contact Details

hugh@surrealdb.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emmanuel-keller** [comment]
With v0.2.0, the transport layer is delegated to the embedded Rust SDK
