### ISSUE TITLE
Feature: Handle json array response from server in refactored WS plaintext protocol

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#68]
### Is your feature request related to a problem?

The SurrealDB protocol can return json arrays for requests of multiple statements.
We currently only handle single responses (i.e. JsonObject).
We should be able to handle JsonArray.

### Describe the solution

In the `SurrealDBWebsocketClientProtocolHandler` in `channelRead0` we should handle the branch for JsonArray response type.

### Alternative methods

None.

### SurrealDB version

1.0.0-beta.9+20230821.0665e1b7 for macos on aarch64

### Contact Details

hugh@surrealdb.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emmanuel-keller** [comment]
Since v0.2.0, the new API supports responses with lists or iterators of values.
https://surrealdb.github.io/surrealdb.java/javadoc/com/surrealdb/Surreal.html
