### ISSUE TITLE
Feature: Handle query returning single responses in the websocket protocol

### ISSUE THREAD

**Issue by phughk** [surrealdb/surrealdb.java#75]
### Is your feature request related to a problem?

The current implementation expects query to return an array of results.
If there is only 1 result, the results field will be a json object not a json array.

### Describe the solution

In the query handling in WsPlaintextConnection handle the possibility that a json object can be returned instead of an array.

### Alternative methods

None

### SurrealDB version

1.0.0-beta.9+20230821.0665e1b7 for macos on aarch64

### Contact Details

hugh@surrealdb.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Divine1** [comment]
@phughk please let me know if this issue is still open or completed
