### ISSUE TITLE
Feature: A complete SDK With Repository pattern

### ISSUE THREAD

**Issue by Mukund2900** [surrealdb/surrealdb.java#82]
### Is your feature request related to a problem?

I want to use this sdk with springboot and need feature like findById and other features which can help me retrieve data directly into the specified DTO. 
In the current scenario the only way to do this is to run a select query and expect list of items and then check if size is 1 or not in the case where i want to fetch by id. 

### Describe the solution

A similar interface like data jpa where we can run queries and autowire that class. 

### Alternative methods

-

### SurrealDB version

1.3.0 for macos on aarch64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by naisofly** [comment]
Hey @Mukund2900! 

While we can do that, they'd be client-side sugar on top of what you could do yourself. 🍭

No worries though, we're always open to new feature requests! 🙌 Just keep in mind that repo patterns are primarily a client concern, so it's not a top priority for now with our regular [releases](https://surrealdb.com/releases). But we'll definitely keep it on the radar!

In the meantime, feel free to share any other ideas you've got brewing. We're all ears 👂🏽😁

**Comment by Mukund2900** [comment]
@naisofly , I kindly request your review of this pull request. It represents just the beginning, with ample opportunity for further enhancements. I welcome your insights and suggestions on the same.
