### ISSUE TITLE
Question: is this project abandoned?

### ISSUE THREAD

**Issue by abccbaandy** [surrealdb/surrealdb.java#87]
### Description

As title.
It's about 1 year since last commit.
And no response to recent issue.
For ex: 
https://github.com/surrealdb/surrealdb.java/issues/86

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HyperCodec** [comment]
Idk but #88 says it was opened 2 days ago, so they must've been doing somethign in the background and maybe just weren't paying attention to github issues.

**Comment by emmanuel-keller** [comment]
Sorry for the silence there!

We started a new implementation a few months ago. The driver becomes a native driver, providing not only a connection to a SurrealDB remote instance but also an embedded in-memory version.

It has been published on Maven Central this morning:
https://central.sonatype.com/artifact/com.surrealdb/surrealdb
